config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  get 'about', to: 'static_pages#about'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  namespace :api, defaults: { format: :json } do
    get 'search', to: 'searches#index'

    resource :session, only: [:show]

    resources :users, only: [:show]

    resources :characters, only: [:show, :index, :create], shallow: true do
      resources :fraction_invitations, only: [:show, :index, :destroy]
    end

    resources :fractions, only: [:show, :index, :create, :update], shallow: true do
      resources :electorates, only: [:show, :index, :create, :destroy]
      resources :positions,   only: [:show, :index, :create, :destroy]
      resources :regions,     only: [:show, :index, :create, :destroy]

      resources :government_authorizations, only: [:create, :destroy]
    end

    resources :electorates, only: [], shallow: true do
      resources :government_authorizations, only: [:create, :destroy]
    end
    resources :positions, only: [], shallow: true do
      resources :government_authorizations, only: [:create, :destroy]
    end
    resources :regions, only: [], shallow: true do
      resources :government_authorizations, only: [:create, :destroy]
    end

    # resources :government_authorizations, only: [:create, :destroy]
    # get 'plot_authorizations/:uuid/:world_id/:x/:z', to: 'plot_authorizations#show'
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <%= link_to "About", about_url %>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to "Home", '/#/' %>
  <% if signed_in? %>
    | <%= link_to "Sign Out", session_url, method: "delete", id: 'sign-out' %>
    | <%= link_to "Account (#{ current_user.name })", '/#/users/' + current_user.id.to_s, id: 'account' %>
    <span class="current-character-header-link"></span>
  <% else %>
    | <%= link_to "Sign Up", new_user_url,    id: 'sign-up' %>
    | <%= link_to "Sign In", new_session_url, id: 'sign-in' %>
  <% end %>
  <br>
  <div class="search">
    <input type="search" placeholder="search" onfocus="Fractions.nameSearch(event)">
  </div>
</header>

app/views/layouts/_messages.html.erb
<div id="flash-messages">
  <% flash.each do |name, messages| %>
    <% messages.each do |message| %>
      <div>
        <%= content_tag :div, message, id: "flash-#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>


<!-- TODO structure doesn't make any sense -->

app/views/layouts/_user_form.html.erb
<form id="user-form" action="<%= url %>" method="post">
  <input type="text" name="user[name]" value="<%= @user.name %>" placeholder="name" autofocus="true" required>
  <br>
  <input type="password" name="user[password]" placeholder="password" required>
  <br>
  <input class="button-primary" type="submit" value="Submit">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Fractions</title>
  <meta name="description" content="The Fractions plugin, for Minecraft">
  <meta name="author" content="Nick Barry">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png'%>
</head>
<body>
  <div class="container">
    <div class="row">
      <%= render "layouts/header" %>
    </div>

    <div class="row">
      <%= render "layouts/messages" %>
    </div>

    <div class="row">
      <%= yield %>
    </div>

    <div class="row">
      <%= render "layouts/footer" %>
    </div>
  </div>
</body>
</html>